pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                script {
                    // Converter o caminho para o formato Unix
                    def workspaceUnixPath = pwd().replace('\\', '/').replace('C:', '/c')
                    echo "Workspace Unix Path: ${workspaceUnixPath}"
                    sh "docker run --rm -v ${workspaceUnixPath}:/workspace -w /workspace maven:3.9.0 mvn -B -DskipTests clean package"
                }
            }
        }
    }
}

